site_name: Shades of India Documentation 
nav:
  - Website Customization:  
    - Intro: 'Website-Customization/Intro.md'
    - Home: 'Website-Customization/Home.md'
    - Header: 'Website-Customization/Header.md'
    - Footer: 'Website-Customization/Footer.md'
    - Collection: 'Website-Customization/Collection.md'
    - Pick of the Day: 'Website-Customization/Pick-of-the-Day.md'
    - WC Lookbooks: 'Website-Customization/WC-lookbooks.md'
  - Products: 
    - Introduction: 'Products/Introduction.md'
    - Add Products: 'Products/Add-Products.md'
    - Import-Export CSV Format: 'Products/Import-Export-CSV-Format.md'
    - Bulk Import: 'Products/Bulk-Import.md'
    - Bulk Export: 'Products/Bulk-Export.md'
  - WooCommerce Settings: 
    - Tax Rate Setup: 'WooCommerce-Settings/Tax-Rate-Setup.md'
  - Delhivery: 'Delhivery.md'
  - Coupons: 'Coupons.md'
  - 2FA Authy Login: '2FA-Authy-Login.md'
theme:
  name: material
  features:
    - instant
  font:
    text: Inter
    code: Source Code Pro
  palette:
      primary: indigo
      accent: blue

plugins:
  - search:
      prebuild_index: true
      lang:
        - en
  - git-revision-date-localized

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
